name: 'Reclaim the bytes'
description: 'Maximize the available disk space for your build job'
branding:
  icon: 'crop'
  color: 'orange'
inputs:
  remove-packages:
    description: 'Remove specified packages'
    required: false
    default: 'dotnet, android, haskell, codeql, docker-images'
runs:
  using: "composite"
  steps:
    - name: Disk space report before modification
      shell: bash
      run: df -h

    - name: Maximize build disk space
      shell: bash
      run: |
        set -euo pipefail

        echo "Arguments:"

        IFS=',' read -ra PACKAGES <<< "${{ inputs.remove-packages }}"
        for i in "${PACKAGES[@]}"; do
          echo "Removing: $i"
          case "$i" in
            'dotnet')
              sudo rm -rf /usr/share/dotnet
              ;;
            'android')
              sudo rm -rf /usr/local/lib/android
              ;;
            'haskell')
              sudo rm -rf /opt/ghc
              ;;
            'codeql')
              sudo rm -rf /opt/hostedtoolcache/CodeQL
              ;;
            'docker-images')
              sudo docker image prune --all --force
              ;;
            'large-packages')
              sudo apt-get purge -y '^llvm-.*' 'php.*' '^mongodb-.*' '^mysql-.*' azure-cli google-cloud-sdk google-chrome-stable firefox powershell microsoft-edge-stable mono-devel
              sudo apt-get autoremove -y
              sudo apt-get clean
              ;;
            *)
              echo "Invalid input: $i"
              ;;
          esac
        done

    - name: Disk space report after modification
      shell: bash
      run: df -h
