name: 'Reclaim The Bytes'
description: 'Remove unused software to reclaim disk space.'
branding:
  icon: 'crop'
  color: 'orange'
inputs:
  remove-dotnet:
    description: 'Remove .NET runtime and libraries. Default: `true`.'
    required: false
    default: 'true'
  remove-android:
    description: 'Remove Android SDKs and Tools. Default: `true`.'
    required: false
    default: 'true'
  remove-haskell:
    description: 'Remove GHC (Haskell) artifacts. Default: `true`.'
    required: false
    default: 'true'
  remove-codeql:
    description: 'Remove CodeQL Action Bundles. Default: `true`.'
    required: false
    default: 'true'
  remove-docker-images:
    description: 'Remove cached Docker images. Default: `true`.'
    required: false
    default: 'true'
  remove-swap:
    description: 'Remove swap. Default: `true`.'
    required: false
    default: 'true'
  remove-boost:
    description: 'Remove boost. Default: `true`.'
    required: false
    default: 'true'
  apt-clean:
    description: 'Run apt-get clean. Default: `true`.'
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Disk space report before modification
      shell: bash
      run: df -h

    - name: Reclaim the bytes
      shell: bash
      run: |
        set -euo pipefail

        if [[ ${{ inputs.remove-dotnet }} == 'true' ]]; then
          echo "Removing dotnet"
          sudo rm -rf /usr/share/dotnet/shared/
          sudo rm -rf /usr/share/dotnet/host/
          sudo rm -rf /usr/share/dotnet/sdk/
        fi

        if [[ ${{ inputs.remove-android }} == 'true' ]]; then
          echo "Removing android"
          sudo rm -rf "$ANDROID_SDK_ROOT"
          sudo rm -rf /usr/local/lib/android
        fi

        if [[ ${{ inputs.remove-haskell }} == 'true' ]]; then
          echo "Removing haskell"
          sudo rm -rf /opt/ghc
        fi

        if [[ ${{ inputs.remove-codeql }} == 'true' ]]; then
          echo "Removing codeql"
          sudo rm -rf /opt/hostedtoolcache/CodeQL
        fi

        if [[ ${{ inputs.remove-docker-images }} == 'true' ]]; then
          echo "Removing Docker images"
          sudo docker image prune --all --force
        fi

        if [[ ${{ inputs.remove-swap }} == 'true' ]]; then
          echo "Removing swap"
          sudo swapoff -a
          sudo rm -f /swapfile
        fi

        if [[ ${{ inputs.remove-boost }} == 'true' ]]; then
          echo "Removing boost"
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        fi

        if [[ ${{ inputs.remove-swift }} == 'true' ]]; then
          echo "Removing swift"
          sudo rm -rf "$SWIFT_PATH"
          sudo rm -rf /usr/share/swift
        fi

        if [[ ${{ inputs.apt-clean }} == 'true' ]]; then
          echo "Run apt-get clean"
          sudo apt-get clean
        fi

        # sudo apt-get purge -y '^llvm-.*' 'php.*' '^mongodb-.*' '^mysql-.*' azure-cli google-cloud-sdk google-chrome-stable firefox powershell microsoft-edge-stable mono-devel

    - name: Disk space report after modification
      shell: bash
      run: df -h
