name: 'Reclaim The Bytes'
description: 'Remove unused software to reclaim disk space.'
branding:
  icon: 'crop'
  color: 'orange'
inputs:
  remove-hosted-tool-cache:
    description: 'Remove the hosted tool cache, including Go, Python, CodeQL, Powershell. Default: `true`.'
    required: false
    default: 'true'
  remove-go:
    description: 'Remove Go libraries. Default: `false`.'
    required: false
    default: 'false'
  remove-python:
    description: 'Remove Python libraries. Default: `false`.'
    required: false
    default: 'false'
  remove-codeql:
    description: 'Remove CodeQL. Default: `false`.'
    required: false
    default: 'false'
  remove-powershell:
    description: 'Remove PowerShell. Default: `false`.'
    required: false
    default: 'false'
  remove-android-sdk:
    description: 'Remove Android SDK. Default: `true`.'
    required: false
    default: 'true'
  remove-haskell-ghc:
    description: 'Remove Haskell GHC. Default: `true`.'
    required: false
    default: 'true'
  remove-swift:
    description: 'Remove Swift. Default: `true`.'
    required: false
    default: 'true'
  remove-dotnet:
    description: 'Remove .NET. Default: `true`.'
    required: false
    default: 'true'
  remove-docker-images:
    description: 'Remove cached Docker images. Default: `true`.'
    required: false
    default: 'true'
  remove-swap:
    description: 'Remove swap. Default: `true`.'
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Disk space report before modification
      shell: bash
      run: df -h

    - name: Remove Hosted Tool Cache
      shell: bash
      if: inputs.remove-hosted-tool-cache == 'true'
      run: |
        sudo rm -rf /opt/hostedtoolcache

    - name: Remove Go
      shell: bash
      if: inputs.remove-go == 'true'
      run: |
        sudo rm -rf /opt/hostedtoolcache/go

    - name: Remove Python
      shell: bash
      if: inputs.remove-python == 'true'
      run: |
        sudo rm -rf /opt/hostedtoolcache/python

    - name: Remove CodeQL
      shell: bash
      if: inputs.remove-codeql == 'true'
      run: |
        sudo rm -rf /opt/hostedtoolcache/CodeQL

    - name: Remove PowerShell
      shell: bash
      if: inputs.remove-powershell == 'true'
      run: |
        sudo rm -rf /usr/local/share/powershell

    - name: Remove Android SDK
      shell: bash
      if: inputs.remove-android-sdk == 'true'
      run: |
        sudo rm -rf /usr/local/lib/android

    - name: Remove Haskell GHC
      shell: bash
      if: inputs.remove-haskell-ghc == 'true'
      run: |
        sudo rm -rf /usr/local/.ghcup/ghc

    - name: Remove Swift
      shell: bash
      if: inputs.remove-swift == 'true'
      run: |
        sudo rm -rf /usr/share/swift

    - name: Remove .NET
      shell: bash
      if: inputs.remove-dotnet == 'true'
      run: |
        sudo rm -rf /usr/share/dotnet

    - name: Remove Docker images
      shell: bash
      if: inputs.remove-docker-images == 'true'
      run: |
        sudo docker image prune --all --force

    - name: Remove Swap
      shell: bash
      if: inputs.remove-swap == 'true'
      run: |
        export SWAP_FILE=$(swapon --show=NAME | tail -n 1)
        sudo swapoff $SWAP_FILE
        sudo rm $SWAP_FILE

    - name: Disk space report after modification
      shell: bash
      run: df -h
