name: 'Reclaim The Bytes'
description: 'Remove unused software to reclaim disk space.'
branding:
  icon: 'crop'
  color: 'orange'
inputs:
  remove-dotnet:
    description: 'Remove .NET runtime and libraries. Default: `true`.'
    required: false
    default: 'true'
  remove-android:
    description: 'Remove Android SDKs and Tools. Default: `true`.'
    required: false
    default: 'true'
  remove-haskell:
    description: 'Remove GHC (Haskell) artifacts. Default: `true`.'
    required: false
    default: 'true'
  remove-codeql:
    description: 'Remove CodeQL Action Bundles. Default: `true`.'
    required: false
    default: 'true'
  remove-docker-images:
    description: 'Remove cached Docker images. Default: `true`.'
    required: false
    default: 'true'
  remove-swap:
    description: 'Remove swap. Default: `true`.'
    required: false
    default: 'true'
  remove-boost:
    description: 'Remove boost. Default: `true`.'
    required: false
    default: 'true'
  apt-clean:
    description: 'Run apt-get clean. Default: `true`.'
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Disk space report before modification
      shell: bash
      run: df -h

    - name: Remove dotnet
      shell: bash
      if: inputs.remove-dotnet == 'true'
      run: |
        sudo rm -rf /usr/share/dotnet/shared/
        sudo rm -rf /usr/share/dotnet/host/
        sudo rm -rf /usr/share/dotnet/sdk/

    - name: Remove android
      shell: bash
      if: inputs.remove-android == 'true'
      run: |
        sudo rm -rf "$ANDROID_SDK_ROOT"
        sudo rm -rf /usr/local/lib/android

    - name: Remove GHC Haskell
      shell: bash
      if: inputs.remove-haskell == 'true'
      run: |
        sudo rm -rf /opt/ghc

    - name: Remove CodeQL
      shell: bash
      if: inputs.remove-codeql == 'true'
      run: |
        sudo rm -rf /opt/hostedtoolcache/CodeQL

    - name: Remove Docker images
      shell: bash
      if: inputs.remove-docker-images == 'true'
      run: |
        sudo docker image prune --all --force

    - name: Remove Swap
      shell: bash
      if: inputs.remove-swap == 'true'
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile

    - name: Remove Boost
      shell: bash
      if: inputs.remove-boost == 'true'
      run: |
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Remove Swift
      shell: bash
      if: inputs.remove-swift == 'true'
      run: |
        sudo rm -rf "$SWIFT_PATH"
        sudo rm -rf /usr/share/swift

    - name: Run apt clean
      shell: bash
      if: inputs.apt-clean == 'true'
      run: |
        sudo apt-get clean

    - name: Disk space report after modification
      shell: bash
      run: df -h
